### ISSUE TITLE
상세페이지에서 이미지 다운로드 버튼 

### ISSUE THREAD

**Issue by suncrud** [team-durumi/kctu-photo#11]

**Comment by suncrud** [comment]
수정하기는 했는데 외부 asset 링크일 경우에 download 태그가 브라우저에서 먹지 않는다는듯 함. 그냥 클릭하면 이미지 뜨는 상태.

**Comment by mozodev** [comment]
오 헤더 추가하면 된다는 듯?
https://stackoverflow.com/questions/17736751/amazon-s3-force-mp3-file-download-bypassing-web-server/25933113#25933113
