### ISSUE TITLE
[production] photo.kctu.org

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kctu-photo#17]
- [x] 넷리파이 계정(아이디 / 비번) - 오늘중으로 달라고 했음. 담당자가 궁금하다고 하시는데, 1월에 미팅에 같이 만나서 설명
- [x] 넷리파이 - main repo - build 연결
- [x] 연결된 넷리파이 url - cname 설정 해 달라고 kctu 담당자에게 요청 
- [x] photo.kctu.org 확인

**Comment by suncrud** [comment]
내일 (화요일)에 전달해준다고 연락받음.
