### ISSUE TITLE
cloudflare 생성 요청 

### ISSUE THREAD

**Issue by suncrud** [team-durumi/kctu-photo#19]
카드 넣으라고 안내

**Comment by woonjjang** [comment]
https://developers.cloudflare.com/r2/platform/pricing/

친절하게 설명해준다.

**Comment by woonjjang** [comment]
[송송님 통화]
- 2022년 개인사정과 내부사정(ICT팀)으로 결제까지 처리는 어려울 것 같다. 
- 우리쪽에 붙여서 올해사업을 마무리하고, 내년 시작 할 때 비용을 어떻게 처리할지(오래 비용도 묻어서) 처리한다.
