### ISSUE TITLE
검색쪽 패싯 ?

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kctu-photo#4]
6) 검색 페이지(https://kctu-photo.durumi.io/search/)
검색 창 하단 흰 공간에 주제/조직/장소/행사/시간 컬렉션에 해당하는 버튼을 무작위로 나열할 수 있을까요? 그래서 각 버튼을 누르면 해당 키워드로 검색된 화면을 보여줄 수 있는지 궁금합니다. 미팅 때 말씀하셨던 것처럼 민주노총 등의 키워드 검색을 지양하게 하려고 하는데요, 혹시 16일 전에 가능하시다면 배치 부탁드립니다.
>> 검색화면에 대한 기획이 달라지게 되어, 업무 범위를 넘어서는 것 같습니다. (2차 사업에서 논의)
>> 이제 막 태그 키워드를 넣고 있는 상황에서 검색화면에 필터를 넣는 것은 어렵습니다.

**Comment by mozodev** [comment]
https://github.com/typesense/typesense
