### ISSUE TITLE
[자료] 12월 16일 오픈 이후 자료 업데이트를 어떻게 할 것인가 ?

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kctu-photo#5]
오늘의 사진 찾다가 없는 구간이 있어서, 아마 사용자가 공개용 nas 쪽에 업데이트를 안 한 것으로 보임. (크로스 체크차)

- 20211125-불평등 사회와 노동의 대응 연구발표회
- 20211125-양경수 민주노총 위원장 석방환영대회

12월 자료 12월 9일까지 안 보임(items 폴더에는 확인되는데..)
- items/12월/_index.md 파일이 생성되어 있지 않아서, 안 보였던 거였음. (해결완료)

**Comment by suncrud** [comment]
나스에 이렇게 생성일이 있네요. 
```
drwxrwxrwx 1   1056 users   216 Dec  1 10:48 '20211125-불평등 사회와 노동의 대응 연구발표회'
drwxrwxrwx 1   1056 users  1.7K Dec 10 15:59 '20211125-양경수 민주노총 위원장 1심 선고 및 석방'
```

그런데 누락된 스프레드시트 목록에 없었음. 
https://docs.google.com/spreadsheets/d/1Vp_Y8mqCWd8Rxibp0tsILuHEtQSBQ9Nm9otS876fAqE/edit#gid=1370428408

**Comment by suncrud** [comment]
이빨빠진 이벤트 발견: 
20210408-민주노총 제7기 성평등강사단 양성교육 1일차
