### ISSUE TITLE
엑셀 조직 term 순서랑 배열 맞춰 달라는 요청

### ISSUE THREAD

**Issue by woonjjang** [team-durumi/kctu-photo#6]
조직 페이지(https://kctu-photo.durumi.io/creators/) 폴더 그림 순서를 조정할 수 있을까요? 조직 순서를 각 조직에서 민감하게 반응할 수 있어서.... ^^; 다른 컬렉션 페이지 내 순서는 나중에 바꾸더라도, 수고스러우시겠지만 16일 오픈 전 조직 컬렉션 페이지는 꼭 수정됐으면 합니다ㅠ 조직 순서는 왼쪽에서 오른쪽 기준, 구글 엑셀파일 NO TOUCH 탭에 있는 순서대로 배열해주시면 좋을 것 같습니다.

**Comment by mozodev** [comment]
```문화예술노동연대``` 는 엑셀에 항목이 없어서 맨뒤로 빼놨...

**Comment by mozodev** [comment]
netlify 빌드가 거의 1시간이 걸려서 이건 좀 아니다 싶어 
vercel을 시도해봤는데 훨씬 빠르네요 보통 12분 빠르면 10분. ㅎ
https://photo-theta.vercel.app/creators

이 뒤 커밋도 있는데 netlify는 또 한 시간을 기다려야한다니 푸시하고 싶어지지가 않는.. ㅎ
게다가 빌드시간도 거의 다 썼... ㅎ

이러느니 차라리 개발머신에서 빌드하고 S3 싱크하는게 훨씬 빠르지 않을까 싶기도.. 
더 빨라야하면 그냥 서버에서 빌드하고 그대로 웹서비스...

**Comment by mozodev** [comment]
```
# vercel hugo build

BUILD COMMAND:
amazon-linux-extras install golang1.11 && hugo mod get -u ./... && hugo --gc --minify

ENV:
HUGO_VERSION
0.91.2
```
